services:
    kunstmaan_user_management.menu.adaptor:
        class: Kunstmaan\UserManagementBundle\Helper\Menu\UserManagementMenuAdaptor
        arguments: ['@security.authorization_checker']
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor', priority: 250 }

    Kunstmaan\UserManagementBundle\EventSubscriber\UserDeleteEventSubscriber:
        arguments:
            - '@kunstmaan_admin.logger'
        tags:
            - { name: 'kernel.event_subscriber' }

    Kunstmaan\UserManagementBundle\Controller\GroupsController:
        arguments: [ '@translator', '@kunstmaan_adminlist.factory' ]
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

    Kunstmaan\UserManagementBundle\Controller\RolesController:
        arguments: [ '@translator', '@kunstmaan_adminlist.factory' ]
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

    Kunstmaan\UserManagementBundle\Controller\UsersController:
        arguments: [ '@translator', '@kunstmaan_adminlist.factory', '@parameter_bag', '@Kunstmaan\AdminBundle\Service\UserManager', '@event_dispatcher' ]
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
