services:
    kunstmaan_user_management.menu.adaptor:
        class: Kunstmaan\UserManagementBundle\Helper\Menu\UserManagementMenuAdaptor
        arguments: ['@security.authorization_checker']
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor', priority: 250 }

    Kunstmaan\UserManagementBundle\EventSubscriber\UserDeleteEventSubscriber:
        arguments:
            - '@kunstmaan_admin.logger'
        tags:
            - { name: 'kernel.event_subscriber' }
